server:
  port: 8090

spring:
  mvc:
    view:
      prefix: /templates
      suffix:
        .html
        .ftl
  datasource:
    url: localhost:3306/springboot
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 564335
    hikari:
      maximum-pool-size: 10
      max-lifetime: 1770000
mybatis:
  type-aliases-package: com.duyi.bean
  configuration:
    map-underscore-to-camel-case: true
    mappper-locations:
      - classpath: mapper/*.xml


