server:
  port: 8090

spring:
  datasource:
    url:
       jdbc:mysql://localhost:3306/guest?characterEncoding=UTF-8&useSSL=false
    username: root
    password: 564335
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  config-location: classpath:mybatis-config.xml




#  jpa:
##    自动创建|更新|验证数据库表结构
#    hibernate:
#      ddl-auto: update
##      设置数据库引擎为InnoDB
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
#    #打印SQL语句 方便调试
#    show-sql: true